name = "analises-trader-api"
main = "index.js"
compatibility_date = "2024-09-01"

# Cron trigger: roda a auditoria a cada hora, dos minutos 5 de cada hora
# (5min depois pra dar tempo dos jogos terminarem antes de buscar resultado)
[triggers]
crons = ["0 * * * *", "*/10 * * * *"]